spring:
  application:
    name: order-pizza-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA}
    show-sql: true
    open-in-view: true
  flyway:
    enabled: true # enables flyway database migration
    locations: classpath:db/migration # the location where flyway should look for migration scripts
    validate-on-migrate: true
    default-schema: ${DB_SCHEMA}
logging:
  level:
    root: info
